### ISSUE TITLE
Mention that Typha or Calico Enterprise is not yet supported

### ISSUE THREAD

**Issue by ry4nz** [Mirantis/mke-docs#202]
@vikramhh please advise what shall be written at:

https://github.com/Mirantis/mke-docs/blob/main/content/docs/concepts/cni.md

**Comment by vikramhh** [comment]
@ry4nz - we could explicitly call out for typha not being supported `MKE 4.0 does not support enabling typha. However unless you are using cluster sizes in excess of 100 nodes, you should not be impacted.`.

Alternatively: `MKE 4.0 uses kdd as networking datastore. Customers may notice degraded networking performance on cluster sizes in excess of 100 nodes. This is a known issue which will be fixed in subsequent releases of MKE 4 by enabling typha`

Typically we document what CNI-s are supported. If we still want to explicitly document the fact that Calico Enterprise is not supported, simply stating the fact (e.g. `MKE 4 does not support upgrading to Calico Enterprise`) should do.

**Comment by KoryKessel-Mirantis** [comment]
Opened https://github.com/Mirantis/mke-docs/pull/208 to work the matter and will close this issue.
